export const MCP_TOOL_CONTRACT_VERSION = "1.0";
export const MCP_TOOL_CONTRACT_VERSION_V1_1 = "1.1";
export const MCP_TOOL_SCHEMA_STABILITY = "stable";
export const PROFILE_EXPORT_SCHEMA_VERSION = 1;

export const MCP_TOOL_NAMES_V1 = Object.freeze([
  "create_player_profile",
  "get_player_profile",
  "list_player_profiles",
  "get_player_stats",
  "refresh_player_stats",
  "update_player_preferences",
  "export_player_profile",
  "import_player_profile",
  "calculate_xp_remaining",
  "get_skill_progress",
  "get_item_price",
  "search_items",
  "get_item_details",
  "get_item_price_history",
  "get_item_buy_limit",
  "get_item_alchemy_value",
  "get_item_price_summary",
  "compare_item_prices",
  "value_item_list",
  "value_equipment_setup",
  "calculate_quest_shopping_cost",
  "calculate_training_cost",
  "export_price_data",
  "refresh_price_data",
  "get_price_data_status",
  "search_quests",
  "get_quest",
  "get_quest_requirements",
  "get_quest_rewards",
  "get_quest_source",
  "set_quest_status",
  "set_multiple_quest_statuses",
  "list_available_quests",
  "list_missing_quest_requirements",
  "create_quest_route",
  "create_quest_shopping_list",
  "refresh_quest_data",
  "get_quest_data_status",
  "list_training_methods",
  "get_training_method",
  "compare_training_methods",
  "create_levelling_plan",
  "create_weekly_goal_plan",
  "estimate_time_to_level",
  "estimate_cost_to_level",
  "compare_quest_xp_rewards",
  "refresh_training_data",
  "get_training_data_status",
] as const);

/**
 * @deprecated Use MCP_TOOL_NAMES_V1. Retained so Version 0.9 consumers can
 * compare their prerelease snapshot without changing imports.
 */
export const MCP_TOOL_NAMES_V0_9 = MCP_TOOL_NAMES_V1;

export const MCP_TOOL_NAMES_V1_1 = Object.freeze([
  ...MCP_TOOL_NAMES_V1,
  "get_system_health",
  "get_provider_health",
  "get_catalogue_health",
  "list_recent_errors",
  "list_recovery_events",
  "retry_failed_operation",
  "refresh_stale_catalogues",
  "run_database_integrity_check",
  "export_redacted_diagnostics",
  "check_for_software_updates",
  "clear_expired_quarantine_records",
  "reset_provider_circuit",
  "get_selected_player_snapshot",
  "set_selected_player_profile",
  "get_player_holdings",
  "replace_player_holdings",
  "upsert_player_holding",
  "import_player_holdings",
  "export_player_holdings",
  "record_ge_trade",
  "list_ge_trades",
  "update_ge_trade",
  "remove_ge_trade",
  "get_market_preferences",
  "update_market_preferences",
  "create_market_watchlist",
  "update_market_watchlist",
  "get_market_watchlist",
  "analyse_ge_item",
  "scan_ge_opportunities",
  "get_ge_buy_candidates",
  "get_ge_sell_candidates",
  "create_manual_ge_order_plan",
  "explain_ge_recommendation",
  "backtest_ge_strategy",
  "get_portfolio_summary",
  "get_real_data_status",
  "refresh_all_real_data",
  "get_market_data_status",
  "refresh_market_data",
  "get_provider_disagreements",
  "set_offline_mode",
  "get_paper_portfolio",
  "record_paper_trade",
  "create_account_aware_quest_shopping_list",
] as const);
