export const MCP_TOOL_CONTRACT_VERSION = "0.9";
export const PROFILE_EXPORT_SCHEMA_VERSION = 1;

export const MCP_TOOL_NAMES_V0_9 = [
  "create_player_profile",
  "get_player_profile",
  "list_player_profiles",
  "get_player_stats",
  "refresh_player_stats",
  "update_player_preferences",
  "export_player_profile",
  "import_player_profile",
  "calculate_xp_remaining",
  "get_skill_progress",
  "get_item_price",
  "search_items",
  "get_item_details",
  "get_item_price_history",
  "get_item_buy_limit",
  "get_item_alchemy_value",
  "get_item_price_summary",
  "compare_item_prices",
  "value_item_list",
  "value_equipment_setup",
  "calculate_quest_shopping_cost",
  "calculate_training_cost",
  "export_price_data",
  "refresh_price_data",
  "get_price_data_status",
  "search_quests",
  "get_quest",
  "get_quest_requirements",
  "get_quest_rewards",
  "get_quest_source",
  "set_quest_status",
  "set_multiple_quest_statuses",
  "list_available_quests",
  "list_missing_quest_requirements",
  "create_quest_route",
  "create_quest_shopping_list",
  "refresh_quest_data",
  "get_quest_data_status",
  "list_training_methods",
  "get_training_method",
  "compare_training_methods",
  "create_levelling_plan",
  "create_weekly_goal_plan",
  "estimate_time_to_level",
  "estimate_cost_to_level",
  "compare_quest_xp_rewards",
  "refresh_training_data",
  "get_training_data_status",
] as const;
