export const SKILL_IDS = [
  "attack",
  "defence",
  "strength",
  "constitution",
  "ranged",
  "prayer",
  "magic",
  "cooking",
  "woodcutting",
  "fletching",
  "fishing",
  "firemaking",
  "crafting",
  "smithing",
  "mining",
  "herblore",
  "agility",
  "thieving",
  "slayer",
  "farming",
  "runecrafting",
  "hunter",
  "construction",
  "summoning",
  "dungeoneering",
  "divination",
  "invention",
  "archaeology",
  "necromancy",
] as const;

export type SkillId = (typeof SKILL_IDS)[number];

export const SKILL_DISPLAY_NAMES: Readonly<Record<SkillId, string>> = {
  attack: "Attack",
  defence: "Defence",
  strength: "Strength",
  constitution: "Constitution",
  ranged: "Ranged",
  prayer: "Prayer",
  magic: "Magic",
  cooking: "Cooking",
  woodcutting: "Woodcutting",
  fletching: "Fletching",
  fishing: "Fishing",
  firemaking: "Firemaking",
  crafting: "Crafting",
  smithing: "Smithing",
  mining: "Mining",
  herblore: "Herblore",
  agility: "Agility",
  thieving: "Thieving",
  slayer: "Slayer",
  farming: "Farming",
  runecrafting: "Runecrafting",
  hunter: "Hunter",
  construction: "Construction",
  summoning: "Summoning",
  dungeoneering: "Dungeoneering",
  divination: "Divination",
  invention: "Invention",
  archaeology: "Archaeology",
  necromancy: "Necromancy",
};
